const assert = require('assert')


// asser.ifError throws message to the console if value is true - which is the same as what happens with errors
assert.ifError(3 == '3')